alercebroker/ztf_explorer

components/cardCrossMatches.vue, pages/object/_oid.vue, store/object.js
=> Add card for xmatch in view of object (issue #194)

components/cardMagStats.vue
=> Fix magnitude values to 3 decimals

components/cardLightCurve.vue
=> Added tooltips for curve selector

api/ztf_api.js, components/cardClassifiers.vue, pages/object/_oid.vue, store/object.js
- Title fixed
- Format probabilities
- Select for classifiers
- Get period from features
=> ADD: Period for lc and probs. plot

components/cardClassifiers.vue
Change from map icon to robot icon
=> CHG: Icon for classifiers

store/filters.js
=> added ranking

pages/object/_oid.vue
=> Showing first avro stamp

store/pagination.js
=> Added default probability desc to result table

components/cardLightCurve.vue
Close #229
- Fix display light curve
- First update library
- To solve: What happen with this lc [ZTF18abuectf](http://dev.alerce.online.s3-website-us-east-1.amazonaws.com/object/ZTF18abuectf)
=> fix apparent light curve. update library

store/filters.js
Set default values for ndet to null
=> fixing ndet

components/cardLightCurve.vue
Close #266
- Download light curve
- Display only band 1 or 2
First you must update component-library
=> input for download lightcurve fixed

pages/index.vue, store/filters.js
=> Fix bugs #234 and #236

plugins/axios.js
=> fix empty string values added to query string

components/cardLightCurve.vue, components/cardStamps.vue, pages/object/_oid.vue, store/lightcurve.js
Closes #192 
- Added selectedDetection to lightcurve store module
- Lightcurve and Stamps components use that state
- Refactored components a bit so that they could be used anywhere across the app
=> added the feature to select detection from stamps and lightcurve

components/objectList.vue, components/simplePagination.vue, layouts/oid.vue, pages/index.vue, pages/object/_oid.vue, store/object.js, store/pagination.js
=> Added object list

components/cardLightCurve.vue
- Update folded lc when period is updated
=> fix update period from API. This trigger if show lc folded

store/filters.js
when you give a list of oids, the result table is in order of respective oids
=> add sort by list of oids

pages/index.vue, store/filters.js
fix problems when in route have only one oid
=> fix when params have only one oid

.env.development, .env.production, .env.staging, .github/workflows/deploy_dev.yml, .github/workflows/deploy_prod.yml, nuxt.config.js, package-lock.json, package.json, plugins/avro.js, plugins/catsHtmApi.js, plugins/tnsApi.js, plugins/ztfApi.js, store/filters.js, store/object.js, store/pagination.js
Defined base urls of apis in `.env` files read using Nuxt's `runtimeConfig`.
Usage described [here](https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#env-support)
=> api base urls defined in env

components/resultsTable.vue, package-lock.json, package.json, pages/index.vue, store/filters.js, store/pagination.js
- Query string now is updated with each parameter change
- Works for pagination, table sorting, search filters (date and conesearch added)
=> query string correctly transformed to params

nuxt.config.js, package.json
Use new component and new (dev) api
=> use new api and new component

nuxt.config.js, package.json, plugins/ztfApi.js, store/lightcurve.js
refactor ztf api request to send the survey_id param.
change the call to the ztf api pluggin with promises
=> feature addind atlas lightcurve

components/errors/authGenericError.vue, components/loginForm.vue, layouts/default.vue, layouts/error.vue, layouts/oid.vue, middleware/auth.js, nuxt.config.js, package-lock.json, pages/login.vue, plugins/users.js, store/user.js, utils/store-accessor.js
- Login with email
- Logout
- Refresh token funcionality
=> Add login with email

components/auth/loginForm.vue, components/auth/registerForm.vue, pages/login.vue, plugins/users.js, store/user.js
=> Add register

package.json
Fix: detections and non detections with unknown fid
=> dev: update component library

components/cardStamps.vue, plugins/avro.js
fix error passing surveyId argument to the store 
renamed the axios request param
=> fix to get avros

components/cardBasicInformation.vue, components/cardClassifiers.vue, components/cardLightCurve.vue, components/cardMagStats.vue, plugins/htmx.js
Cambios:
- Se modificó la card classifiers con el fin de llamar a la API probability con Htmx
- Se eliminó los "watch" de los componentes
=> Probability API call Htmx
